apiVersion: v1
kind: Pod
metadata:
  name: test-local-vol
  labels:
    name: test-local-vol
spec:
  containers:
  - name: app
    image: raesene/windows-powertools
    command:
    - powershell.exe
    - -command
    - "start-sleep -seconds 600"
    volumeMounts:
      - name: local-persistent-storage
        mountPath: /mnt
  volumes:
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: test-pvc
  nodeSelector:
    kubernetes.io/os: windows